# Generated by Django 3.2 on 2021-04-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtype',
            options={'verbose_name_plural': 'Item Types'},
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
